---
dependencies:
  - role: nova.core.docker
    vars:
      # Temporary fix where Docker 29+ does not pull the Providentia image correctly after Vault has been composed or vice versa
      docker_engine_version: 28
