---
- name: Checking if reboot is required...
  ansible.windows.win_shell: Test-PendingReboot -SkipConfigurationManagerClientCheck | Select-Object -ExpandProperty IsRebootPending
  changed_when: false
  register: pending_reboot

- name: Running reboot recheck tasks...
  when: pending_reboot.stdout_lines[0] == 'True'
  block:
    - name: Rebooting & rechecking...
      ansible.windows.win_reboot:
        reboot_timeout: 1200 # Temp FIX for Exchange long reboots when running Elastic Agent

    - name: Re-including check_and_reboot task...
      ansible.builtin.include_tasks: check_and_reboot.yml
