---
docker_engine_version: {}
docker_daemon_template: daemon.json

# Docker daemon.json defaults
docker_data_root: {} # Default is /var/lib/docker but can be changed to a different location
docker_enable_experimental_features: true
docker_buildkit: true
docker_enable_ipv6: true
docker_enable_ip6tables: true
docker_enable_iptables: true
docker_bridge_ipv6_range: fd69::/64
docker_userland_proxy: true
docker_log_to_journald: false

# List of mirrors to be added to the Docker daemon config. The mirror must be a complete URL including a protocol (http:// or https://)
docker_registry_mirrors: []

# List of Docker networks to be create
docker_create_network: true
docker_network:
  name: local-network
  enable_ipv6: true
  ipv4_subnet: 172.18.0.0/16
  ipv6_subnet: fd42::/64

# Docker APT proxy
docker_apt_proxy: https://download.docker.com/linux/{{ ansible_distribution | lower }}
