---
#########
# Linux #
#########

# Default docker daemon.json template to be used
# Update the path if you have a custom template
docker_daemon_template: daemon.json

# Docker daemon.json defaults
docker_data_root: {} # Default is /var/lib/docker but can be changed to a different location
docker_enable_experimental_features: true
docker_buildkit: true
docker_enable_ipv6: true
docker_enable_ip6tables: true
docker_enable_iptables: true
docker_firewall_backend: iptables # Options are iptables or still experimental nftables
docker_bridge_ipv6_range: fd69::/64
docker_userland_proxy: true
docker_log_to_journald: false

# List of mirrors to be added to the Docker daemon config.
# The mirror must be a complete URL including a protocol eg https://
docker_registry_mirrors: []

# Docker networks to be created by default
# Set docker_networks: [] to disable default network creation
# For more advanced use cases use the following module separately after this role
# https://docs.ansible.com/projects/ansible/latest/collections/community/docker/docker_network_module.html
docker_networks:
  - name: local-network
    enable_ipv6: true
    ipv4_subnet: 172.18.0.0/16
    ipv6_subnet: fd42::/64

#############
# Debian OS #
#############

# Default is latest version available in the Docker APT repository but can be locked to a specific major version
docker_engine_version: {}

# Docker APT proxy
docker_apt_proxy: https://download.docker.com/linux/{{ ansible_facts.distribution | lower }}

# Mapping for non-default Debian OS based distributions like Kali, Parrot, etc.
# This is used to set the correct distribution and codename for the Docker APT repository
docker_non_default_debian_os_list:
  - Kali
  - Parrot
