---
- name: Checking if Prefech service exists...
  ansible.windows.win_service:
    name: SysMain
  register: sysmain_state

- name: Stopping prefetch...
  ansible.windows.win_service:
    name: SysMain
    state: stopped
  when: sysmain_state.exists # Does not exists for older Server CORE OS

- name: Stopping Windows Update service...
  ansible.windows.win_service:
    name: wuauserv
    state: stopped
  register: stopping_windows_update_service
  until: stopping_windows_update_service.failed != "false"
  retries: 5
  delay: 3

- name: Stopping Update Orchestrator Service...
  ansible.windows.win_service:
    name: UsoSvc
    state: stopped
  when: ansible_facts.distribution_version is version('6.3.9600.0', '>') # Greater than Windows 8.1 & Server 2012 R2

- name: Cleaning up Windows machine logs...
  ansible.windows.win_shell: "{{ lookup('template', 'Windows-Cleanup.ps1') }}"
  register: windows_cleanup
  until: windows_cleanup.rc == 0
  retries: 10
  delay: 12

- name: Setting reboot_on_finalize to true... # This will reboot the VM during nova.core.finalize role
  ansible.builtin.set_fact:
    reboot_on_finalize: true
  when: cleanup_post_reboot
