---
template_os_configuration_sysprep: true # Will run sysprep on Windows machines if set to true
template_os_configuration_install_chocolatey: true # Set to false to skip Chocolatey installation
template_os_configuration_remove_extra_cdroms_on_vsphere: true # Find and remove extra cdroms on vSphere if there are more than 1
template_os_configuration_update_system: true # Update OS during this role

# Increasing MaxAuthTries in sshd_config to avoid issues where user has more then 6 keys in their SSH agent
template_os_configuration_increase_maxauthtries: true
template_os_configuration_increase_maxauthtries_value: 20

# Will create a fresh snapshot after all configuration is done on the template VM
# Set to false to skip snapshot creation
template_os_configuration_create_snapshot: true

# By default will remove all previous snapshots and create a new one
# Set value to "snap" to avoid removing previous snapshots
template_os_configuration_create_snapshot_mode: clean-snap

# Name of the snapshot to create after configuration is done. Only used if template_os_configuration_create_snapshot is true
template_os_configuration_create_snapshot_name: LinkedCloneSource
