---
- name: Checking if {{ customization_role_path }}/{{ role }} role exists...
  ansible.builtin.stat:
    path: "{{ customization_role_path }}/{{ role }}"
  register: role_existence
  become: false
  delegate_to: localhost

- name: Checking if {{ customization_role_path }}/{{ role }} exists and including the role...
  when: role_existence.stat.exists
  block:
    - name: Creating {{ post_scripts_folder_on_target }} folder...
      ansible.windows.win_file:
        path: "{{ post_scripts_folder_on_target }}"
        state: directory
      when:
        - ansible_facts.system is defined
        - ansible_facts.system == "Win32NT"

    - name: Including {{ customization_role_path }}/{{ role }} role...
      ansible.builtin.include_role:
        name: "{{ customization_role_path }}/{{ role }}"

- name: Flushing handlers...
  ansible.builtin.meta: flush_handlers

- name: Getting IP and ending play...
  when: role_only | bool
  block:
    - name: Including get_ip role...
      ansible.builtin.include_role:
        name: nova.core.get_ip

    - name: Ending play for role_only...
      ansible.builtin.meta: end_host
