---
# Linux Debian
debian_family_updates_allow_reboot: true
debian_family_unattended_upgrades: true
debian_family_unattended_upgrades_allow_reboot: false
reboot_on_finalize: false

# Windows

# Which update categories to install
# https://docs.ansible.com/ansible/latest/collections/ansible/windows/win_updates_module.html#parameter-category_names
updates_category_names: "*"
