---
################
# Linux Debian #
################

# Allow rebooting the system after running this role
debian_family_updates_allow_reboot: true

# Enabling auto updates for Debian family
debian_family_unattended_upgrades: true

# Allow automatically rebooting the system when auto updates are enabled
debian_family_unattended_upgrades_allow_reboot: false

# Upgrade method for Debian family
updates_debian_family_upgrade_method: dist

################
# Linux RedHat #
################

# Nr of kernel versions to keep, since by default RedHat boot partition is only 1GB
updates_redhat_family_nr_of_kernels_to_keep: 2

###########
# Windows #
###########

# Which update categories to install
# https://docs.ansible.com/ansible/latest/collections/ansible/windows/win_updates_module.html#parameter-category_names
updates_category_names: "*"

########
# MISC #
########

# Default value for reboot_on_finalize variable that is used to reboot the system during `nova.core.finalize` role
reboot_on_finalize: false

###########
# FreeBSD #
###########

# FreeBSD does not have an automatic way of detecting if a reboot is required after updates
# This variable can be set to true to always reboot after updates are applied
# This is required because some updates will stop services like VMTools or QEMU Guest Agent from working properly until the system is rebooted
updates_freebsd_reboot_after_updates: true
