---
- name: Including snapshot tasks...
  delegate_to: localhost
  become: false
  block:
    - name: Including powerstate role...
      ansible.builtin.include_role:
        name: nova.core.powerstate
      vars:
        shutdown: true
      when:
        - snapshot_mode in ['clean-snap', 're-snap', 'snap']
        - not live_snap | bool

    - name: Removing the latest snapshot snapshot...
      community.proxmox.proxmox_snap:
        hostname: "{{ custom_vm_name | default(vm_name) }}"
        snapname: "{{ (snapshot_info.json.data | map(attribute='name'))[0] }}"
        state: absent
        validate_certs: "{{ proxmox_validate_certs }}"
      when:
        - snapshot_mode == 're-snap'
        - (snapshot_info.json.data | map(attribute='name'))[0] != 'current'

    - name: Getting the time...
      ansible.builtin.setup:
        filter: "*_time"

    - name: Creating a snapshot for {{ custom_vm_name | default(vm_name) }}...
      community.proxmox.proxmox_snap:
        hostname: "{{ custom_vm_name | default(vm_name) }}"
        state: present
        # Using Snapshot- prefix and regex_replace tp make sure the default snapshot name fit's the Proxmox naming convention
        snapname: "{{ snapshot_name | default('Snapshot-' + ansible_facts.date_time.iso8601) | regex_replace(':', '-') }}"
        description: Created at {{ ansible_facts.date_time.iso8601 | regex_replace(':', '-') }} by {{ project_deployer_username | default(deployer_username) }}
        retention: "{{ 1 if snapshot_mode == 'clean-snap' else omit }}"
        vmstate: "{{ true if live_snap else false }}" # Memory dump
        timeout: "{{ proxmox_machine_operations_operation_timeout }}"
        validate_certs: "{{ proxmox_validate_certs }}"

- name: Including powerstate role...
  ansible.builtin.include_role:
    name: nova.core.powerstate
  vars:
    poweron: true
  when:
    - start_vm_after_snapshot | bool # To be able to pass this as a cli extra var -e start_vm_after_snapshot=true/false
    - not live_snap | bool # To be able to pass this as a cli extra var -e live_snap=true/false
