---
- name: Adding Docker repo key for {{ ansible_facts.distribution_release }}...
  ansible.builtin.get_url:
    url: "{{ docker_apt_proxy }}/gpg"
    dest: /etc/apt/trusted.gpg.d/docker.asc
    mode: "0644"
  register: docker_repo_key
  until: not docker_repo_key.failed # Because sometimes the primary DNS is not up yet or egress FW is still being deployed
  retries: 10
  delay: 6
  vars:
    # Overriding ansible_facts.distribution and ansible_facts.distribution_release to match Debian
    ansible_facts:
      distribution_release: bookworm
      distribution: Debian

# Using copy because ansible.builtin.apt_repository does not have a feature to override existing repository in *.list file
- name: Adding Docker repository...
  ansible.builtin.copy:
    content: deb [arch=amd64] {{ docker_apt_proxy }} {{ ansible_facts.distribution_release }} stable
    dest: /etc/apt/sources.list.d/docker.list
    mode: "0644"
  vars:
    # Overriding ansible_facts.distribution and ansible_facts.distribution_release to match Debian
    ansible_facts:
      distribution_release: bookworm
      distribution: Debian
