---
- name: Setting connection to SSH...
  ansible.builtin.set_fact:
    ansible_connection: ssh

- name: Copying trusted certificates(s) to {{ inventory_hostname }}...
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: /usr/local/share/ca-certificates/{{ item.name }}.crt
    mode: "0644"
  loop: "{{ trusted_certificates_list }}"
  loop_control:
    label: /usr/local/share/ca-certificates/{{ item.name }}.crt
  become: true
  when: not item.src.startswith('http')

- name: Downloading trusted certificates(s) to {{ inventory_hostname }}...
  ansible.builtin.get_url:
    url: "{{ item.src }}"
    dest: /usr/local/share/ca-certificates/{{ item.name }}.crt
    mode: "0644"
    timeout: 60
    validate_certs: "{{ trusted_certificates_validate_certs }}"
  loop: "{{ trusted_certificates_list }}"
  loop_control:
    label: /usr/local/share/ca-certificates/{{ item.name }}.crt
  become: true
  when: item.src.startswith('http')

- name: Updating CA certificates...
  ansible.builtin.command: update-ca-certificates
  become: true
  changed_when: true

- name: Setting connection back to {{ default_connection_plugin }}...
  ansible.builtin.set_fact:
    ansible_connection: "{{ default_connection_plugin }}"
