---
- name: Install host dependencies
  ansible.builtin.package:
    name:
      - git
      - make

- name: Check if previous installation is prebuilt
  ansible.builtin.stat:
    path: "{{ providentia_install_dir }}/docker-compose.yml"
  register: providentia_prebuilt_compose_file

- name: Stop previous installation
  community.docker.docker_compose_v2:
    project_src: "{{ providentia_install_dir }}"
    state: absent
    wait: true
  when: providentia_prebuilt_compose_file.stat.exists

- name: Clear previous installation dir
  ansible.builtin.file:
    path: "{{ providentia_install_dir }}"
    state: absent
  when: providentia_prebuilt_compose_file.stat.exists

- name: Check for leftover git dir
  ansible.builtin.stat:
    path: "{{ providentia_install_dir_git }}"
  register: providentia_pre_existing_git_dir

- name: Clear previous git dir
  ansible.builtin.file:
    path: "{{ providentia_install_dir_git }}"
    state: absent
  when: providentia_pre_existing_git_dir.stat.exists

- name: Clone Providentia repo
  ansible.builtin.git:
    accept_hostkey: true
    repo: https://github.com/ClarifiedSecurity/Providentia.git
    dest: "{{ providentia_install_dir }}"
    version: "{{ providentia_deploy_branch }}"
    force: true
    separate_git_dir: "{{ providentia_install_dir_git }}"

- name: Test if using newer image with entrypoint set on image
  ansible.builtin.command: "grep ENTRYPOINT {{ providentia_install_dir }}/Dockerfile"
  ignore_errors: true
  register: entrypoint_present

- name: Template Providentia configuration
  ansible.builtin.template:
    src: "{{ conf.src }}"
    dest: "{{ providentia_install_dir }}/{{ conf.dest | default(conf.src) }}"
    lstrip_blocks: true
    mode: "0644"
  loop_control:
    loop_var: conf
  loop:
    - src: .makerc-vars
    - src: docker-compose.yml
      dest: docker/prod/
  vars:
    cmd_and_entrypoint_needed: "{{ entrypoint_present.rc != 0 }}"

- name: Replace app URI-s in keycloak config
  ansible.builtin.replace:
    path: "{{ providentia_install_dir }}/docker/prod/providentia.yaml"
    regexp: 'providentia\.localhost'
    replace: "{{ providentia_app_fqdn }}"
  when: providentia_builtin_keycloak

- name: Remove old version info
  ansible.builtin.file:
    path: "{{ providentia_install_dir }}/CURRENT_VERSION"
    state: absent

- name: Build Providentia image, start containers
  community.general.make:
    chdir: "{{ providentia_install_dir }}"
    target: "{{ build }}"
  loop_control:
    loop_var: build
  loop:
    - build
    - start
