---
customization_role_path: "{{ inventory_dir }}/vm" # Root path where too look for the role folder(s). Relative to where the inventory file is located.
role: "{{ inventory_hostname }}" # Name of the role folder under the customization_role_path to look for and include
