---
services:
  gitlab:
    container_name: gitlab
    hostname: gitlab-container
    image: gitlab/gitlab-ee:{{ gitlab_version | default('latest') }}
    restart: always
    ports:
      - "{{ gitlab_ssh_port }}:22"
    volumes:
      - "{{ gitlab_config_folder }}/etc:/etc/gitlab"
      - "{{ gitlab_config_folder }}/logs:/var/log/gitlab"
      - "{{ gitlab_config_folder }}/data:/var/opt/gitlab"
      - "{{ gitlab_config_folder }}/registry:/var/opt/gitlab/gitlab-rails/shared/registry"
      - "{{ gitlab_config_folder }}/temp_configuration:/temp_configuration"
      - "{{ gitlab_config_folder }}/sshd_config:/assets/sshd_config"
      - "/srv/certs:/srv/certs"
      - "/usr/local/share/ca-certificates:/usr/local/share/ca-certificates"
      # GitLab keeps custom certs in this folder https://docs.gitlab.com/omnibus/settings/ssl.html#troubleshooting
      - "/usr/local/share/ca-certificates:/etc/gitlab/trusted-certs"

    # Overriding the default healthcheck values to allow longer startup times on low end machines
    # https://gitlab.com/gitlab-org/omnibus-gitlab/-/blob/master/docker/Dockerfile#L81-82
    healthcheck:
      test: /opt/gitlab/bin/gitlab-healthcheck --fail --max-time 10
      interval: 60s
      retries: 10
      timeout: 30s

    shm_size: "1G"
    environment:
      GITLAB_OMNIBUS_CONFIG: "from_file('/omnibus_config.rb')"
    configs:
      - source: gitlab
        target: /omnibus_config.rb

    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65535
        hard: 65535

    logging:
      driver: json-file
      options:
        max-size: 250m
        max-file: "1"

configs:
  gitlab:
    file: ./gitlab.rb

networks:
  default:
    name: "{{ gitlab_docker_network }}"
    external: true
