---
# Package Installation
- name: Installing universal Linux packages...
  ansible.builtin.package:
    name:
      - ca-certificates
      - curl
      - file
      - htop
      - jq
      - kitty-terminfo # To pass your terminal settings over ssh
      - mc
      - nano
      - net-tools
      - nftables
      - perl
      - python3
      - sudo
      - tcpdump
      - traceroute
      - vim
      - wget
      - cloud-guest-utils # Required for expanding disks
    state: present

- name: Include Ubuntu specific configuration...
  ansible.builtin.include_tasks: ubuntu.yml
  when: ansible_distribution == 'Ubuntu'

- name: Include Debian based OS specific configuration...
  ansible.builtin.include_tasks: debian_based_os.yml
  when: ansible_facts.os_family == "Debian"

# SSHD Configuration
- name: Increasing SSHD MaxAuthTries to 20... # This to avoid erros when someone has more that 6 SSH keys in their agent
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: .*MaxAuthTries.*
    line: MaxAuthTries 20

# GRUB Configuration
- name: Change GRUB timeout
  ansible.builtin.lineinfile:
    path: /etc/default/grub
    regexp: ^GRUB_TIMEOUT=
    line: GRUB_TIMEOUT=2

# Network Configuration for networkd
- name: Enabling DHCP for IPv6...
  ansible.builtin.lineinfile:
    dest: /etc/network/interfaces
    line: iface ens192 inet6 dhcp
  when: (ansible_distribution == 'Debian') or (ansible_distribution == 'Kali')

# Cleaning up current machine ID
- name: Removing machine-id files...
  ansible.builtin.file:
    name: "{{ item }}"
    state: absent
  loop:
    - /etc/machine-id
    - /var/lib/dbus/machine-id

- name: Creating a new empty machine-id file...
  ansible.builtin.file:
    path: /etc/machine-id
    mode: "0644"
    state: touch

- name: Creating a symlink for machine-id in /var/lib/dbus/machine-id...
  ansible.builtin.file:
    src: /etc/machine-id
    dest: /var/lib/dbus/machine-id
    mode: "0644"
    state: link
