---
- name: Encoding Administrator's password...
  ansible.windows.win_shell: "{{ lookup('ansible.builtin.template', 'Encode-UnattendPassword.ps1') }}"
  register: win_shell

- name: Templating C:/Windows/System32/Sysprep/Unattend.xml...
  ansible.windows.win_template:
    src: Unattend.xml
    dest: C:/Windows/System32/Sysprep/Unattend.xml

- name: Running Sysprep...
  ansible.windows.win_shell: "{{ lookup('ansible.builtin.template', 'Windows-Sysprep.ps1') }}"
  async: 60
  poll: 0
