---
- name: Disabling password requirement for sudo...
  ansible.builtin.lineinfile:
    dest: /usr/local/etc/sudoers.d/sudoers
    state: present
    regexp: ^%admins
    line: "%admins ALL=(ALL) NOPASSWD: ALL"
    validate: visudo -cf %s
    create: true
    mode: "0600"
  when: not sudo_requires_password

- name: Enabling password requirement for sudo...
  ansible.builtin.lineinfile:
    dest: /usr/local/etc/sudoers.d/sudoers
    state: present
    regexp: ^%admins
    line: "%admins ALL=(ALL:ALL) ALL"
    validate: visudo -cf %s
    create: true
    mode: "0600"
  when: sudo_requires_password

# Configuring Opnsense accounts in localhost to avoid installing required Python modules on the remote host
- name: Downloading config.xml from {{ inventory_hostname }}...
  ansible.builtin.fetch:
    dest: /tmp/{{ project_fullname | default('') }}_{{ inventory_hostname }}_opnsense_config.xml
    src: /conf/config.xml
    flat: true

- name: Re-creating users and adding them to groups...
  delegate_to: localhost
  become: false
  block:
    - name: Deleting existing users...
      community.general.xml:
        path: /tmp/{{ project_fullname | default('') }}_{{ inventory_hostname }}_opnsense_config.xml
        xpath: /opnsense/system/user
        state: absent

    - name: Deleting existing admins group members...
      community.general.xml:
        path: /tmp/{{ project_fullname | default('') }}_{{ inventory_hostname }}_opnsense_config.xml
        xpath: /opnsense/system/group[name='admins']/member
        state: absent

    - name: Including custom sudoers file for {{ inventory_hostname }}...
      community.general.xml:
        path: /tmp/{{ project_fullname | default('') }}_{{ inventory_hostname }}_opnsense_config.xml
        xpath: /opnsense/installedpackages/sudo/config/add_includedir
        value: include_end
        pretty_print: true
      when: not sudo_requires_password

    - name: Not including custom sudoers file for {{ inventory_hostname }}...
      community.general.xml:
        path: /tmp/{{ project_fullname | default('') }}_{{ inventory_hostname }}_opnsense_config.xml
        xpath: /opnsense/installedpackages/sudo/config/add_includedir
        value: none
        pretty_print: true
      when: sudo_requires_password

    - name: Adding following Opnsense users for {{ inventory_hostname }}...
      community.general.xml:
        path: /tmp/{{ project_fullname | default('') }}_{{ inventory_hostname }}_opnsense_config.xml
        xpath: /opnsense/system
        pretty_print: true
        add_children:
          - user:
              _:
                - name: "{{ item.username }}"
                - descr: "{{ 'System Administrator' if item.username == admin_account else item.username }}"
                - scope: "{{ 'system' if item.username == admin_account else 'user' }}"
                - groupname: admins
                - password: "{{ item.password | password_hash('sha512') }}"
                - authorizedkeys: "{{ (item.ssh_key | b64encode) if item.ssh_key is defined else '' }}"
                - shell: "{{ '/usr/local/sbin/opnsense-shell' if item.username == admin_account else '/bin/tcsh' }}"
                - uid: "{{ (0 if item.username == admin_account else 2000 + idx - 1) | string }}"
      loop: "{{ admin_accounts_with_password }}"
      loop_control:
        index_var: idx
        label: "{{ item.username }}"

    - name: Adding following OPNsense users to admins group for {{ inventory_hostname }}...
      community.general.xml:
        path: /tmp/{{ project_fullname | default('') }}_{{ inventory_hostname }}_opnsense_config.xml
        xpath: /opnsense/system/group[name='admins']
        pretty_print: true
        add_children:
          - member: "{{ (0 if item.username == admin_account else 2000 + idx - 1) | string }}"
      loop: "{{ admin_accounts_with_password }}"
      loop_control:
        index_var: idx
        label: "{{ item.username }}"

- name: Uploading config.xml to {{ inventory_hostname }}...
  ansible.builtin.copy:
    src: /tmp/{{ project_fullname | default('') }}_{{ inventory_hostname }}_opnsense_config.xml
    dest: /conf/config.xml
    mode: "0644"
    owner: root
    group: wheel

- name: Removing local config.xml file...
  ansible.builtin.file:
    path: /tmp/{{ project_fullname | default('') }}_{{ inventory_hostname }}_opnsense_config.xml
    state: absent
  delegate_to: localhost
  become: false

# This is required because sometimes the new configuration will apply on upload and Ansible will try to connect to the host again with invalid credentials
- name: Restarting {{ custom_vm_name | default(vm_name) }} VM...
  ansible.builtin.include_role:
    name: nova.core.powerstate
  vars:
    restart: true

- name: Setting correct password for {{ ansible_deployer_username }}...
  ansible.builtin.set_fact:
    ansible_deployer_password: "{{ admin_accounts_with_password
      | selectattr('username', 'equalto', ansible_deployer_username) | map(attribute='password') | first }}"

- name: Waiting until ssh is down for {{ inventory_hostname }}...
  ansible.builtin.wait_for:
    host: "{{ ansible_host }}"
    port: 22
    state: stopped
    timeout: 300
  delegate_to: localhost
  become: false

- name: Waiting until ssh is up for {{ inventory_hostname }}...
  ansible.builtin.wait_for:
    host: "{{ ansible_host }}"
    port: 22
    state: started
    timeout: 300
  delegate_to: localhost
  become: false

- name: Waiting for VMware tools to become available...
  community.vmware.vmware_guest_tools_wait:
    name: "{{ custom_vm_name | default(vm_name) }}"
  delegate_to: localhost
  become: false
  when: infra_env | default('') == "vsphere"
