---
- name: Listing user accounts created with {{ ansible_role_name }}...
  ansible.builtin.shell: |
    for profile in /home/*/; do
        if [ -e $profile/.created ]; then
            echo $(basename $profile)
        fi
    done
  register: home_profiles
  changed_when: false

- name: Getting profiles not defined in accounts list...
  ansible.builtin.set_fact:
    user_profiles_to_remove: "{{ home_profiles.stdout_lines | difference(local_accounts_with_password | map(attribute='username')) }}"

- name: Trying to remove stale accounts...
  block:
    - name: Removing following accounts...
      ansible.builtin.user:
        name: "{{ item }}"
        state: absent
        remove: true
        force: true
      loop: "{{ user_profiles_to_remove }}"

  # Using rescue to close any open sessions before trying to remove accounts again
  rescue:
    - name: Rebooting again to close any other open sessions...
      ansible.builtin.reboot:
      when:
        - user_profiles_to_remove != []
        - accounts_reboot_before_remove | bool

    - name: Removing following accounts...
      ansible.builtin.user:
        name: "{{ item }}"
        state: absent
        remove: true
        force: true
      loop: "{{ user_profiles_to_remove }}"
